In [18]:
import polars as pl
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import date

In [3]:
import kagglehub

path = kagglehub.dataset_download("desolution01/messy-employee-dataset")

In [4]:
csv_file = [f for f in os.listdir(path) if f.endswith(".csv")][0]

In [5]:
df = pl.read_csv(os.path.join(path,csv_file))

In [6]:
df.columns

['Employee_ID',
 'First_Name',
 'Last_Name',
 'Age',
 'Department_Region',
 'Status',
 'Join_Date',
 'Salary',
 'Email',
 'Phone',
 'Performance_Score',
 'Remote_Work']

In [7]:
df.head(100)

shape: (100, 12)
┌────────────┬────────────┬───────────┬──────┬───┬────────────┬────────────┬───────────┬───────────┐
│ Employee_I ┆ First_Name ┆ Last_Name ┆ Age  ┆ … ┆ Email      ┆ Phone      ┆ Performan ┆ Remote_Wo │
│ D          ┆ ---        ┆ ---       ┆ ---  ┆   ┆ ---        ┆ ---        ┆ ce_Score  ┆ rk        │
│ ---        ┆ str        ┆ str       ┆ i64  ┆   ┆ str        ┆ i64        ┆ ---       ┆ ---       │
│ str        ┆            ┆           ┆      ┆   ┆            ┆            ┆ str       ┆ bool      │
╞════════════╪════════════╪═══════════╪══════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ EMP1000    ┆ Bob        ┆ Davis     ┆ 25   ┆ … ┆ bob.davis@ ┆ -165162319 ┆ Average   ┆ true      │
│            ┆            ┆           ┆      ┆   ┆ example.co ┆ 7          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ m          ┆            ┆           ┆           │
│ EMP1001    ┆ Bob        ┆ Brown     ┆ null ┆ … ┆ bob.brown@ ┆ -189847139 ┆ Excellent ┆ true      │
│            ┆            ┆           ┆      ┆   ┆ example.co ┆ 0          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ m          ┆            ┆           ┆           │
│ EMP1002    ┆ Alice      ┆ Jones     ┆ null ┆ … ┆ alice.jone ┆ -559636321 ┆ Good      ┆ true      │
│            ┆            ┆           ┆      ┆   ┆ s@example. ┆ 1          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ com        ┆            ┆           ┆           │
│ EMP1003    ┆ Eva        ┆ Davis     ┆ 25   ┆ … ┆ eva.davis@ ┆ -347649078 ┆ Good      ┆ true      │
│            ┆            ┆           ┆      ┆   ┆ example.co ┆ 4          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ m          ┆            ┆           ┆           │
│ EMP1004    ┆ Frank      ┆ Williams  ┆ 25   ┆ … ┆ frank.will ┆ -158673425 ┆ Poor      ┆ false     │
│            ┆            ┆           ┆      ┆   ┆ iams@examp ┆ 6          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ le.com     ┆            ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …    ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ EMP1095    ┆ Heidi      ┆ Miller    ┆ 25   ┆ … ┆ heidi.mill ┆ -461033993 ┆ Average   ┆ true      │
│            ┆            ┆           ┆      ┆   ┆ er@example ┆ 6          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ .com       ┆            ┆           ┆           │
│ EMP1096    ┆ Frank      ┆ Johnson   ┆ 40   ┆ … ┆ frank.john ┆ -886140578 ┆ Average   ┆ false     │
│            ┆            ┆           ┆      ┆   ┆ son@exampl ┆ 5          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ e.com      ┆            ┆           ┆           │
│ EMP1097    ┆ Frank      ┆ Brown     ┆ 40   ┆ … ┆ frank.brow ┆ -170630489 ┆ Excellent ┆ false     │
│            ┆            ┆           ┆      ┆   ┆ n@example. ┆ 0          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ com        ┆            ┆           ┆           │
│ EMP1098    ┆ Bob        ┆ Miller    ┆ null ┆ … ┆ bob.miller ┆ -382496718 ┆ Excellent ┆ false     │
│            ┆            ┆           ┆      ┆   ┆ @example.c ┆ 2          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ om         ┆            ┆           ┆           │
│ EMP1099    ┆ Eva        ┆ Jones     ┆ 25   ┆ … ┆ eva.jones@ ┆ -258238686 ┆ Good      ┆ false     │
│            ┆            ┆           ┆      ┆   ┆ example.co ┆ 9          ┆           ┆           │
│            ┆            ┆           ┆      ┆   ┆ m          ┆            ┆           ┆           │
└────────────┴────────────┴───────────┴──────┴───┴────────────┴────────────┴───────────┴───────────┘

In [8]:
print(df.schema)
print(df.null_count())
print(df.glimpse())

Schema({'Employee_ID': String, 'First_Name': String, 'Last_Name': String, 'Age': Int64, 'Department_Region': String, 'Status': String, 'Join_Date': String, 'Salary': String, 'Email': String, 'Phone': Int64, 'Performance_Score': String, 'Remote_Work': Boolean})
shape: (1, 12)
┌─────────────┬────────────┬───────────┬─────┬───┬───────┬───────┬───────────────────┬─────────────┐
│ Employee_ID ┆ First_Name ┆ Last_Name ┆ Age ┆ … ┆ Email ┆ Phone ┆ Performance_Score ┆ Remote_Work │
│ ---         ┆ ---        ┆ ---       ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---               ┆ ---         │
│ u32         ┆ u32        ┆ u32       ┆ u32 ┆   ┆ u32   ┆ u32   ┆ u32               ┆ u32         │
╞═════════════╪════════════╪═══════════╪═════╪═══╪═══════╪═══════╪═══════════════════╪═════════════╡
│ 0           ┆ 0          ┆ 0         ┆ 211 ┆ … ┆ 0     ┆ 0     ┆ 0                 ┆ 0           │
└─────────────┴────────────┴───────────┴─────┴───┴───────┴───────┴───────────────────┴─────────────┘
Rows: 1020
Columns: 12
$ Employee_ID        <str> 'EMP1000', 'EMP1001', 'EMP1002', 'EMP1003', 'EMP1004', 'EMP1005', 'EMP1006', 'EMP1007', 'EMP1008', 'EMP1009'
$ First_Name         <str> 'Bob', 'Bob', 'Alice', 'Eva', 'Frank', 'Alice', 'Frank', 'Bob', 'Frank', 'Charlie'
$ Last_Name          <str> 'Davis', 'Brown', 'Jones', 'Davis', 'Williams', 'Garcia', 'Jones', 'Jones', 'Davis', 'Johnson'
$ Age                <i64> 25, null, null, 25, 25, 40, null, 30, 35, null
$ Department_Region  <str> 'DevOps-California', 'Finance-Texas', 'Admin-Nevada', 'Admin-Nevada', 'Cloud Tech-Florida', 'Sales-Texas', 'Admin-Nevada', 'Cloud Tech-Florida', 'Admin-Nevada', 'DevOps-New York'
$ Status             <str> 'Active', 'Active', 'Pending', 'Inactive', 'Active', 'Inactive', 'Active', 'Inactive', 'Inactive', 'Active'
$ Join_Date          <str> '4/2/2021', '7/10/2020', '12/7/2023', '11/27/2021', '1/5/2022', '6/10/2020', '4/3/2020', '7/17/2022', '12/8/2023', '8/4/2022'
$ Salary             <str> '59767.65', '65304.66', '88145.9', '69450.99', '109324.61', '88642.84', '96288.43', '94497.91', '115565.82', '76561.88'
$ Email              <str> 'bob.davis@example.com', 'bob.brown@example.com', 'alice.jones@example.com', 'eva.davis@example.com', 'frank.williams@example.com', 'alice.garcia@example.com', 'frank.jones@example.com', 'bob.jones@example.com', 'frank.davis@example.com', 'charlie.johnson@example.com'
$ Phone              <i64> -1651623197, -1898471390, -5596363211, -3476490784, -1586734256, -5409003485, -4518376063, -4134327559, -4177656123, -8156985699
$ Performance_Score  <str> 'Average', 'Excellent', 'Good', 'Good', 'Poor', 'Good', 'Good', 'Average', 'Excellent', 'Excellent'
$ Remote_Work       <bool> True, True, True, True, False, False, False, True, True, True

None

In [26]:

def split_department_region(df: pl.DataFrame) -> pl.DataFrame:

    return (
        df.with_columns(
            pl.col("Department_Region").str.split("-").list.get(0).alias("Department"),
            pl.col("Department_Region").str.split("-").list.get(1).alias("Region"),
        )
        .drop("Department_Region")
    )


def parse_dates(df: pl.DataFrame, cols: list[str], fmt: str) -> pl.DataFrame:

    return df.with_columns([
        pl.col(c).str.to_date(fmt, strict=False).alias(c)
        for c in cols
    ])


def cast_numeric(df: pl.DataFrame, schema: dict[str, pl.DataType]) -> pl.DataFrame:


    return df.with_columns([
        pl.col(c).cast(t, strict=False)
        for c, t in schema.items()
    ])


def nullify_invalid(df: pl.DataFrame, col: str, condition) -> pl.DataFrame:

    return df.with_columns(
        pl.when(condition)
          .then(None)
          .otherwise(pl.col(col))
          .alias(col)
    )


def fill_nulls_median(df: pl.DataFrame, cols: list[str]) -> pl.DataFrame:

    return df.with_columns([
        pl.col(c).fill_null(pl.col(c).median().cast(pl.Int64))
        for c in cols
    ])


def cast_enum(df: pl.DataFrame, schema: dict[str, list[str]]) -> pl.DataFrame:

    return df.with_columns([
        pl.col(c).cast(pl.Enum(vals))
        for c, vals in schema.items()
    ])



def drop_empty_columns(df: pl.DataFrame) -> pl.DataFrame:
    return df[[c for c in df.columns if df[c].null_count() < len(df)]]


def deduplicate(df: pl.DataFrame, subset: list[str], keep: str = "first") -> pl.DataFrame:
    n_before = len(df)
    n_dupes = df.filter(pl.col(subset[0]).is_duplicated()).shape[0]

    if n_dupes == 0:
        print(f"no duplicates found on {subset} - 0 duplicate rows, 0 dropped.")
        print(f"Rows before: {n_before}. Rows after: {n_before}")
        return df

    df = df.unique(subset = subset, keep=keep)

    n_after = len(df)
    n_dropped = n_before - n_after

    print(f"Duplicated found on {subset}: {n_dupes} duplicated rows, {n_dropped} dropped.")
    print(f"Rows before {n_before}. Rows after {n_after}")

    return df

def validate_emails(df: pl.DataFrame, col: str = "Email") -> pl.DataFrame:
    email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

    n_before = df[col].null_count()


    #nulify any email that does not match the pattern

    df = df.with_columns(pl.when(pl.col(col).str.contains(email_pattern)).then(pl.col(col)).otherwise(None).alias(col))

    n_after = df[col].null_count()
    n_invalid = n_after - n_before

    if n_invalid == 0:
        print(f"Email Validation: 0 invalid emails found")
    else:
        print(f"Email validation: {n_invalid} invalid emails nullified")

    return df

def add_tenure(df: pl.DataFrame, join_date_col: str = "Join_Date") -> pl.DataFrame:
    today = pl.lit(date.today())

    return df.with_columns(((today - pl.col(join_date_col)).dt.total_days()/365).cast(pl.Int32).alias("Tenure_Years"))
    
    
def add_salary_band(df: pl.DataFrame, col: str= "Salary") -> pl.DataFrame:

    p33 = df[col].quantile(0.33)
    p66 = df[col].quantile(0.66)

    return df.with_columns(pl.when(pl.col(col) < p33).then(pl.lit("Low")).when(pl.col(col) < p66).then(pl.lit("Mid")).otherwise(pl.lit("High")).cast(pl.Categorical).alias("Salary Band"))

def run_pipeline(df: pl.DataFrame) -> pl.DataFrame:

    # Step 1 — split compound column into Department and Region
    df = split_department_region(df)

    # Step 2 — parse Join_Date from M/D/YYYY string format to pl.Date
    df = parse_dates(df, cols=["Join_Date"], fmt="%m/%d/%Y")

    # Step 3 — cast Salary from string to float
    df = cast_numeric(df, {"Salary": pl.Float64})

    # Step 4 — nullify Phone values that are negative (corrupted data)
    df = nullify_invalid(df, "Phone", pl.col("Phone") < 0)

    #Step 5 - drop empty columns
    df = drop_empty_columns(df)  # drops Phone since it's 100% null
    
    # Step 6 — fill Age nulls with median (211 nulls found in triage)
    df = fill_nulls_median(df, ["Age"])

    # Step 7 — enforce known category sets for Status and Performance_Score
    df = cast_enum(df, {
        "Status": ["Active", "Inactive", "Pending"],
        "Performance_Score": ["Poor", "Average", "Good", "Excellent"]
    })

    #step 8 ensure unique employee id's drop duplicate records
    df = deduplicate(df,subset=["Employee_ID"], keep="first")

    #step 9 vailidating the emails
    df = validate_emails(df, col="Email")

    #Step 10 get the number of years worked based on the date joined
    df = add_tenure(df, join_date_col="Join_Date")

    #Step 11 segment the income to low mid high
    df = add_salary_band(df, col="Salary")
    
    return df


# --- Run the pipeline ---
df_clean = run_pipeline(df)

# Verify results
print(df_clean.schema)       # confirm if all dtypes are correct
print(df_clean.null_count()) # checking for null count

no duplicates found on ['Employee_ID'] - 0 duplicate rows, 0 dropped.
Rows before: 1020. Rows after: 1020
Email Validation: 0 invalid emails found
Schema({'Employee_ID': String, 'First_Name': String, 'Last_Name': String, 'Age': Int64, 'Status': Enum(categories=['Active', 'Inactive', 'Pending']), 'Join_Date': Date, 'Salary': Float64, 'Email': String, 'Performance_Score': Enum(categories=['Poor', 'Average', 'Good', 'Excellent']), 'Remote_Work': Boolean, 'Department': String, 'Region': String, 'Tenure_Years': Int32, 'Salary Band': Categorical})
shape: (1, 14)
┌─────────────┬────────────┬───────────┬─────┬───┬────────────┬────────┬─────────────┬─────────────┐
│ Employee_ID ┆ First_Name ┆ Last_Name ┆ Age ┆ … ┆ Department ┆ Region ┆ Tenure_Year ┆ Salary Band │
│ ---         ┆ ---        ┆ ---       ┆ --- ┆   ┆ ---        ┆ ---    ┆ s           ┆ ---         │
│ u32         ┆ u32        ┆ u32       ┆ u32 ┆   ┆ u32        ┆ u32    ┆ ---         ┆ u32         │
│             ┆            ┆           ┆     ┆   ┆            ┆        ┆ u32         ┆             │
╞═════════════╪════════════╪═══════════╪═════╪═══╪════════════╪════════╪═════════════╪═════════════╡
│ 0           ┆ 0          ┆ 0         ┆ 0   ┆ … ┆ 0          ┆ 0      ┆ 0           ┆ 0           │
└─────────────┴────────────┴───────────┴─────┴───┴────────────┴────────┴─────────────┴─────────────┘

In [24]:
df_clean.head()

shape: (5, 14)
┌─────────────┬─────────────┬───────────┬─────┬───┬─────────────┬────────────┬────────────┬────────┐
│ Employee_ID ┆ First_Name  ┆ Last_Name ┆ Age ┆ … ┆ Department  ┆ Region     ┆ Tenure_Yea ┆ Salary │
│ ---         ┆ ---         ┆ ---       ┆ --- ┆   ┆ ---         ┆ ---        ┆ rs         ┆ Band   │
│ str         ┆ str         ┆ str       ┆ i64 ┆   ┆ str         ┆ str        ┆ ---        ┆ ---    │
│             ┆             ┆           ┆     ┆   ┆             ┆            ┆ i32        ┆ cat    │
╞═════════════╪═════════════╪═══════════╪═════╪═══╪═════════════╪════════════╪════════════╪════════╡
│ EMP1000     ┆ Bob         ┆ Davis     ┆ 25  ┆ … ┆ DevOps      ┆ California ┆ 5          ┆ low    │
│ EMP1001     ┆ Bob         ┆ Brown     ┆ 30  ┆ … ┆ Finance     ┆ Texas      ┆ 5          ┆ low    │
│ EMP1002     ┆ Alice       ┆ Jones     ┆ 30  ┆ … ┆ Admin       ┆ Nevada     ┆ 2          ┆ medium │
│ EMP1003     ┆ Eva         ┆ Davis     ┆ 25  ┆ … ┆ Admin       ┆ Nevada     ┆ 4          ┆ low    │
│ EMP1004     ┆ Frank       ┆ Williams  ┆ 25  ┆ … ┆ Cloud Tech  ┆ Florida    ┆ 4          ┆ high   │
└─────────────┴─────────────┴───────────┴─────┴───┴─────────────┴────────────┴────────────┴────────┘

In [27]:
df_clean.group_by("Salary Band").len().sort("Salary Band")

shape: (3, 2)
┌─────────────┬─────┐
│ Salary Band ┆ len │
│ ---         ┆ --- │
│ cat         ┆ u32 │
╞═════════════╪═════╡
│ High        ┆ 363 │
│ Low         ┆ 328 │
│ Mid         ┆ 329 │
└─────────────┴─────┘